---
- name: Deploy Project Fetch (App, Nginx, and Worker)
  hosts: fetch_app
  remote_user: root
  tasks:
    # 1. Capture the current branch name on the control node
    - name: Get current git branch name
      delegate_to: localhost
      ansible.builtin.command: git rev-parse --abbrev-ref HEAD
      register: current_git_branch
      changed_when: false

    # 2. Switch the control node to the target branch
    - name: Ensure control node is on the correct branch
      delegate_to: localhost
      ansible.builtin.shell: |
        # Get current branch name
        current_branch=$(git rev-parse --abbrev-ref HEAD)
        # Only checkout if the requested version is different
        if [ "$current_branch" != "{{ fetch_app_version }}" ]; then
          git checkout {{ fetch_app_version }}
        fi
      args:
        chdir: ~/fetch-control
      changed_when: false

    - name: Ensure app and media directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
      loop:
        - /root/fetch-app/templates
        - /opt/fetch-app/scripts
        - /var/www/fetch/media/highres
        - /var/www/fetch/media/lowres

    - name: Ensure uv is installed on the container
      ansible.builtin.shell: curl -LsSf https://astral.sh/uv/install.sh | sh
      args:
        creates: /root/.local/bin/uv

    - name: Find uv binary path
      ansible.builtin.command: which uv
      register: uv_path
      changed_when: false
      failed_when: uv_path.rc != 0

    - name: Run Goose Migrations
      delegate_to: localhost
      ansible.builtin.shell:
        cmd: goose -dir migrations mysql "root:password@tcp(192.168.50.60:3306)/fetch_db" up
        chdir: ~/fetch-control

    - name: Sync FastAPI Application Files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0644'
      loop:
        - { src: 'main.py', dest: '/root/fetch-app/main.py' }
        - { src: 'templates/dashboard.html', dest: '/root/fetch-app/templates/dashboard.html' }
        - { src: 'pyproject.toml', dest: '/root/fetch-app/pyproject.toml' }
        - { src: 'uv.lock', dest: '/root/fetch-app/uv.lock' }
        - { src: 'templates/bin_view.html', dest: '/root/fetch-app/templates/bin_view.html' }
        - { src: 'templates/print_labels.html', dest: '/root/fetch-app/templates/print_labels.html' }
        - { src: 'templates/global_search.html', dest: '/root/fetch-app/templates/global_search.html' }
        - { src: 'templates/admin.html', dest: '/root/fetch-app/templates/admin.html' }
        - { src: 'find_orphans.py', dest: '/root/fetch-app/find_orphans.py' }
      notify: Restart Fetch

    - name: Ensure MySQL Connector is in uv environment
      ansible.builtin.command:
        cmd: "{{ uv_path.stdout }} add mysql-connector-python"
        chdir: /root/fetch-app
      register: uv_add_result
      changed_when: "'Added' in uv_add_result.stdout"

    - name: Sync uv environment (uv sync)
      ansible.builtin.command:
        cmd: "{{ uv_path.stdout }} sync"
        chdir: /root/fetch-app
      register: uv_sync_result
      changed_when: "'Successfully' in uv_sync_result.stdout"

    - name: Deploy Image Worker Script
      ansible.builtin.copy:
        src: scripts/process_images.py
        dest: /opt/fetch-app/scripts/process_images.py
        mode: '0755'

    - name: Deploy Nginx Site Configuration
      ansible.builtin.copy:
        dest: /etc/nginx/sites-available/fetch
        content: |
          server {
              listen 80;
              server_name _;
              client_max_body_size 20M;

              location / {
                  proxy_pass http://127.0.0.1:8000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              location /media/ {
                  alias /var/www/fetch/media/;
                  autoindex on;
              }
          }
      register: nginx_config

    - name: Disable default Nginx site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Enable Fetch Nginx site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/fetch
        dest: /etc/nginx/sites-enabled/fetch
        state: link
        force: yes

    - name: Restart Nginx if config changed
      ansible.builtin.service:
        name: nginx
        state: restarted
      when: nginx_config.changed

    # 3. Deploy Systemd Units with the captured version variable
    - name: Deploy Systemd Units from templates
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        mode: '0644'
      loop:
        - fetch.service
      vars:
        app_version_label: "{{ current_git_branch.stdout }}"
      notify: Reload Systemd

    - name: Ensure Services are Running and Enabled
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - fetch
        - fetch-image-worker.timer

    - name: Commit deployment record to Git
      delegate_to: localhost
      ansible.builtin.shell: |
        git add .
        git commit -m "Automated Deploy: Branch versioning implementation" || exit 0
      ignore_errors: yes

  handlers:
    - name: Reload Systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart Fetch
      ansible.builtin.systemd:
        name: fetch
        state: restarted
