---
- name: Deploy Project Fetch (App, Nginx, and Worker)
  hosts: fetch_app
  remote_user: root
  tasks:
    - name: Ensure app and media directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
      loop:
        - /root/fetch-app/templates
        - /opt/fetch-app/scripts
        - /var/www/fetch/media/highres
        - /var/www/fetch/media/lowres

    - name: Ensure uv is installed on the container
      ansible.builtin.shell: curl -LsSf https://astral.sh/uv/install.sh | sh
      args:
        creates: /root/.local/bin/uv

    - name: Find uv binary path
      ansible.builtin.command: which uv
      register: uv_path
      changed_when: false
      failed_when: uv_path.rc != 0

    - name: Run Goose Migrations
      delegate_to: localhost  # Runs from your control container where goose is installed
      ansible.builtin.shell:
        cmd: goose -dir migrations mysql "root:password@tcp(192.168.50.60:3306)/fetch_db" up
        chdir: ~/fetch-control  # Path to your migrations folder

    - name: Sync FastAPI Application Files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0644'
      loop:
        - { src: 'main.py', dest: '/root/fetch-app/main.py' }
        - { src: 'templates/dashboard.html', dest: '/root/fetch-app/templates/dashboard.html' }
        - { src: 'pyproject.toml', dest: '/root/fetch-app/pyproject.toml' }
        - { src: 'uv.lock', dest: '/root/fetch-app/uv.lock' }
        - { src: 'templates/bin_view.html', dest: '/root/fetch-app/templates/bin_view.html' }
        - { src: 'templates/print_labels.html', dest: '/root/fetch-app/templates/print_labels.html' }
        - { src: 'templates/global_search.html', dest: '/root/fetch-app/templates/global_search.html' }
        - { src: 'templates/admin.html', dest: '/root/fetch-app/templates/admin.html' }
        - { src: 'find_orphans.py', dest: '/root/fetch-app/find_orphans.py' }
      notify: Restart Fetch

    - name: Ensure MySQL Connector is in uv environment
      ansible.builtin.command:
        cmd: "{{ uv_path.stdout }} add mysql-connector-python"
        chdir: /root/fetch-app
      register: uv_add_result
      changed_when: "'Added' in uv_add_result.stdout"

    - name: Sync uv environment (uv sync)
      ansible.builtin.command:
        cmd: "{{ uv_path.stdout }} sync"
        chdir: /root/fetch-app
      register: uv_sync_result
      changed_when: "'Successfully' in uv_sync_result.stdout"

    - name: Deploy Image Worker Script
      ansible.builtin.copy:
        src: scripts/process_images.py
        dest: /opt/fetch-app/scripts/process_images.py
        mode: '0755'

    - name: Deploy Nginx Site Configuration
      ansible.builtin.copy:
        dest: /etc/nginx/sites-available/fetch
        content: |
          server {
              listen 80;
              server_name _;
              client_max_body_size 20M; # Increase upload limit for high-res photos

              location / {
                  proxy_pass http://127.0.0.1:8000; # Send traffic to the FastAPI app
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              location /media/ {
                  alias /var/www/fetch/media/; # Still serve static media directly
                  autoindex on;
              }
          }

      register: nginx_config

    - name: Disable default Nginx site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Enable Fetch Nginx site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/fetch
        dest: /etc/nginx/sites-enabled/fetch
        state: link
        force: yes

    - name: Restart Nginx if config changed
      ansible.builtin.service:
        name: nginx
        state: restarted
      when: nginx_config.changed

    - name: Deploy Systemd Units from templates
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        mode: '0644'
      loop:
        - fetch.service
      notify: Reload Systemd

    - name: Ensure Services are Running and Enabled
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - fetch
        - fetch-image-worker.timer

    - name: Commit deployment record to Git
      delegate_to: localhost
      ansible.builtin.shell: |
        git add .
        git commit -m "Automated Deploy: Finalized paths and uv binary discovery" || exit 0
      ignore_errors: yes

  handlers:
    - name: Reload Systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart Fetch
      ansible.builtin.systemd:
        name: fetch
        state: restarted
