---
- name: Install Fetch Base Stack
  hosts: all
  gather_facts: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MariaDB, Nginx, and Python dependencies
      apt:
        name:
          - mariadb-server
          - nginx
          - python3-pip
          - python3-pymysql
        state: present

    - name: Ensure MariaDB and Nginx are running
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - mariadb
        - nginx

    - name: Configure Nginx Gallery View
      copy:
        dest: /etc/nginx/sites-available/fetch
        content: |
          server {
              listen 80;
              server_name _;

              root /var/www/fetch;

              location / {
                  autoindex on;
                  autoindex_exact_size off;
                  autoindex_format html;
                  autoindex_localtime on;
              }

              location /media/ {
                  autoindex on;
              }
          }
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
